import pandas as pd
from pathlib import Path
import base64

def image_to_base64(img_path: str) -> str:
    with open(img_path, "rb") as img_file:
        return base64.b64encode(img_file.read()).decode('utf-8')

def generate_html_report(summary_html: str, plots: dict, output_path: str):
    """
    Generate a standalone HTML report.
    plots: dict of {name: path}
    """
    
    # Encode images
    img_tags = ""
    for name, path in plots.items():
        if Path(path).exists():
            b64 = image_to_base64(path)
            img_tags += f"""
            <div class="chart-container">
                <h3>{name}</h3>
                <img src="data:image/png;base64,{b64}" alt="{name}">
            </div>
            """
            
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>M&A Health Forecast - Executive Briefing</title>
        <style>
            body {{ font-family: 'Segoe UI', Arial, sans-serif; color: #333; margin: 0; padding: 0; background-color: #f4f4f4; }}
            .container {{ max_width: 1200px; margin: 40px auto; background: white; padding: 40px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); border-radius: 8px; }}
            h1 {{ color: #005587; border-bottom: 2px solid #FFB81C; padding-bottom: 10px; }}
            h3 {{ color: #005587; margin-top: 30px; }}
            .summary-box {{ background-color: #f8f9fa; border-left: 5px solid #005587; padding: 20px; margin-bottom: 30px; }}
            .chart-grid {{ display: grid; grid-template-columns: 1fr; gap: 30px; }}
            .chart-container {{ background: white; padding: 10px; border: 1px solid #eee; border-radius: 4px; }}
            img {{ max_width: 1000%; height: auto; display: block; margin: 0 auto; }}
            .footer {{ margin-top: 50px; font-size: 0.8em; color: #777; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>M&A Health Forecast: Executive Briefing</h1>
            
            <div class="summary-box">
                {summary_html}
            </div>
            
            <div class="chart-grid">
                {img_tags}
            </div>
            
            <div class="footer">
                Generated by M&A Health Analytics Engine | Confidential
            </div>
        </div>
    </body>
    </html>
    """
    
    with open(output_path, "w") as f:
        f.write(html_content)
    print(f"Report generated at {output_path}")
